# -*- coding: utf-8 -*-
"""Ejecucion completa

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10JKfOU0uRvl6zwyYEXYFa2ljblVCvZtX
"""

# 📌 Script Maestro para ejecutar todas las tareas (Colab o GitHub Actions)

import os

# 🔍 Detectar si estamos en Google Colab
try:
    from google.colab import auth, drive
    IN_COLAB = True
except ImportError:
    IN_COLAB = False

if IN_COLAB:
    print("✅ Ejecutando en Google Colab")
    # 🔑 Autenticación
    auth.authenticate_user()
    # 📂 Montar Google Drive
    drive.mount('/content/drive')
    # Ruta de scripts en Google Drive
    RUTA_SCRIPTS = "/content/drive/MyDrive/Colab Notebooks"
else:
    print("✅ Ejecutando fuera de Colab (ej. GitHub Actions)")
    # Ruta de scripts dentro del repo (ajústala si tus .py están en otra carpeta)
    RUTA_SCRIPTS = "."

# 📜 Lista de scripts a ejecutar
scripts = [
    "CreditosActivos10.py",
    "Rentabilidad.py",
    "Detallado de Canje.py",
    "Kpis's.py"
]

# ▶️ Ejecutar cada script
for script in scripts:
    ruta_script = os.path.join(RUTA_SCRIPTS, script)
    print(f"\n🚀 Ejecutando: {script}")
    try:
        with open(ruta_script, "r", encoding="utf-8") as file:
            exec(file.read())
        print(f"✅ {script} completado.")
    except Exception as e:
        print(f"❌ Error al ejecutar {script}:", e)

print("\n🎯 Todas las tareas han sido ejecutadas.")