name: Subir datos a BigQuery

on:
  push:
    branches:
      - main

jobs:
  subir_bigquery:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar repo
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install google-cloud-bigquery pandas

    - name: Autenticar Google Cloud
      env:
        GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      run: |
        echo "$GCP_CREDENTIALS" > $HOME/gcp_credentials.json
        export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcp_credentials.json

    - name: Ejecutar script
      run: |
        python tu_script.py
      env:
        GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcp_credentials.json
