name: Desplegar Looker Studio

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GCP_CREDENTIALS_B64: ${{ secrets.GCP_CREDENTIALS_B64 }}

    steps:
      - name: Revisar código
        uses: actions/checkout@v4

      - name: Instalar gcloud
        run: |
          curl https://sdk.cloud.google.com | bash > /dev/null
          source $HOME/google-cloud-sdk/path.bash.inc
          gcloud --version

      - name: Decodificar credenciales
        run: |
          echo "$GCP_CREDENTIALS_B64" | base64 --decode > credentials.json
          cat credentials.json

      - name: Autenticar con GCP
        run: |
          gcloud auth activate-service-account --key-file=credentials.json
          gcloud config set project $(jq -r '.project_id' credentials.json)

      - name: Desplegar Looker Studio
        run: |
          chmod +x ./deploy.sh
          ./deploy.sh
